---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iperf-server
spec:
  selector:
    matchLabels:
      app: iperf-server
  replicas: 1
  template:
    metadata:
      labels:
        app: iperf-server
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app 
                operator: In
                values:
                - iperf-client
            topologyKey: "kubernetes.io/hostname"
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-l4
      tolerations:
      - operator: Exists
      containers:
      - name: iperf-server
        image: ubuntu:latest
        command:
        - /bin/bash
        - -c
        - |
          apt update && apt install iperf -y
          iperf -s
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: iperf-server
spec:
  selector:
    app: iperf-server
  ports:
   - protocol: TCP
     port: 5001
     targetPort: 5001